<?xml version="1.0" encoding="utf-8"?>
<Control>
   <Log>
      <Messages />
      <Exceptions>
         <Exception Id="12/01/2021 10:56:28 a. m." Tipo="Excepcion" Time="12/01/21 10:56:28" Descripcion="Failure sending mail." Metodo="Send" Trace="   at System.Net.Mail.SmtpClient.Send(MailMessage message)&#xD;&#xA;   at KCM.ServiciosInternet.Plugins.Business.Logica.clsPlugInLogInServices.sendEmailToUser(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\KCM.ServiciosInternet.Plugins.Business\Logica\clsPlugInLogInServices.cs:line 57&#xD;&#xA;   at KCM.ServiciosInternet.Plugins.Business.Logica.clsPlugInLogInServices.requestResetPassword(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\KCM.ServiciosInternet.Plugins.Business\Logica\clsPlugInLogInServices.cs:line 30&#xD;&#xA;   at KCM.ServiciosInternet.Plugins.Business.BussinessResetPs.requestResetPassword(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\KCM.ServiciosInternet.Plugins.Business\BussinessResetPs.cs:line 21&#xD;&#xA;   at WcfLogInGiGya.Services.ResetPS.requestResetPassword(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\WcfLogInGiGya\Services\resetPS.svc.cs:line 38" Mensaje="Se ha producido una excepción en WcfLogInGiGya/Services/resetPS/requestResetPassword" />
         <Exception Id="12/01/2021 10:56:28 a. m." Tipo="Excepcion" Time="12/01/21 10:56:28" Descripcion="Unable to connect to the remote server" Metodo="GetConnection" Trace="   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress&amp; address, Socket&amp; abortSocket, Socket&amp; abortSocket6)&#xD;&#xA;   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)&#xD;&#xA;   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)&#xD;&#xA;   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)&#xD;&#xA;   at System.Net.Mail.SmtpClient.GetConnection()&#xD;&#xA;   at System.Net.Mail.SmtpClient.Send(MailMessage message)" Mensaje="Se ha producido una excepción en WcfLogInGiGya/Services/resetPS/requestResetPassword" />
         <Exception Id="12/01/2021 10:56:28 a. m." Tipo="Excepcion" Time="12/01/21 10:56:28" Descripcion="A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.140.45.4:25" Metodo="DoConnect" Trace="   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)&#xD;&#xA;   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)" Mensaje="Se ha producido una excepción en WcfLogInGiGya/Services/resetPS/requestResetPassword" />
         <Exception Id="12/01/2021 11:07:01 a. m." Tipo="Excepcion" Time="12/01/21 11:07:01" Descripcion="Failure sending mail." Metodo="Send" Trace="   at System.Net.Mail.SmtpClient.Send(MailMessage message)&#xD;&#xA;   at KCM.ServiciosInternet.Plugins.Business.Logica.clsPlugInLogInServices.sendEmailToUser(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\KCM.ServiciosInternet.Plugins.Business\Logica\clsPlugInLogInServices.cs:line 57&#xD;&#xA;   at KCM.ServiciosInternet.Plugins.Business.Logica.clsPlugInLogInServices.requestResetPassword(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\KCM.ServiciosInternet.Plugins.Business\Logica\clsPlugInLogInServices.cs:line 30&#xD;&#xA;   at KCM.ServiciosInternet.Plugins.Business.BussinessResetPs.requestResetPassword(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\KCM.ServiciosInternet.Plugins.Business\BussinessResetPs.cs:line 21&#xD;&#xA;   at WcfLogInGiGya.Services.ResetPS.requestResetPassword(ResetPassWordData objData) in C:\KCM\Servicios de Internet\KCM.ServiciosInternet.Plugins\WcfLogInGiGya\Services\resetPS.svc.cs:line 38" Mensaje="Se ha producido una excepción en WcfLogInGiGya/Services/resetPS/requestResetPassword" />
         <Exception Id="12/01/2021 11:07:01 a. m." Tipo="Excepcion" Time="12/01/21 11:07:01" Descripcion="Unable to connect to the remote server" Metodo="GetConnection" Trace="   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress&amp; address, Socket&amp; abortSocket, Socket&amp; abortSocket6)&#xD;&#xA;   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)&#xD;&#xA;   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)&#xD;&#xA;   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)&#xD;&#xA;   at System.Net.Mail.SmtpClient.GetConnection()&#xD;&#xA;   at System.Net.Mail.SmtpClient.Send(MailMessage message)" Mensaje="Se ha producido una excepción en WcfLogInGiGya/Services/resetPS/requestResetPassword" />
         <Exception Id="12/01/2021 11:07:01 a. m." Tipo="Excepcion" Time="12/01/21 11:07:01" Descripcion="A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.140.45.4:25" Metodo="DoConnect" Trace="   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)&#xD;&#xA;   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)" Mensaje="Se ha producido una excepción en WcfLogInGiGya/Services/resetPS/requestResetPassword" />
      </Exceptions>
   </Log>
   <Debug>
      <DebugMessages />
   </Debug>
</Control>